# Generated by Django 5.2.8 on 2025-11-13 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('usn', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('Subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('enroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.student')),
                ('Subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.subject')),
            ],
        ),
    ]
